# Generated by Django 4.1.1 on 2023-02-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='MusicHistory',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
