# Generated by Django 4.1.1 on 2023-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='Customuser',
            new_name='user',
        ),
    ]
