version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres_db
  postgres_db:
    image: postgres
    restart: always
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # my-api:
  #   build:
  #     context: ./../api # chemin vers le dossier contenant votre fichier Dockerfile
  #     dockerfile: Dockerfile # nom de votre fichier Dockerfile
  #   ports:
  #     - "8080:8001" # ports à exposer pour votre API
  #   volumes:
  #     - ./../api/:/app # chemin vers votre dossier contenant votre application API

volumes:
  postgres_data:
