channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=22.2.2
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.1
  - psutil==5.9.4
  - scikit-learn==1.2.0
  - typing-extensions==4.4.0
  - xgboost==1.7.2
name: mlflow-env
